name: Docker

on:
  push:
  pull_request:

env:
  PRODUCTION_REF: refs/heads/main
  CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: service-account.json

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: google-github-actions/setup-gcloud@v1
        with:
          # temp fix for a `gcloud auth` error:
          # gcloud crashed (AttributeError): 'bool' object has no attribute 'lower'
          version: "< 405.0.0"
      - run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > $CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
      - run: make docker/login
      # so we can leverage caching during the build phase
      - run: make docker/pull || true
      - run: make docker/build
      - name: docker push
        if: github.ref == env.PRODUCTION_REF
        run: make docker/push
